### PR TITLE
fix "assignment count mismatch: 3 = 2"

### PR DESCRIPTION
**Pull request by nwolff**
This fixes the "Assignment count mismatch: 3 = 2" compilation error introduced in 368fb46cb7fec929d69b5c865baa81b5598b3966

Now the situation is back to what it was before that pull-request: the zip file does not get closed, but at least it compiles.

Would you want me to create a wercker CI configuration so that the code is compiled and tested after each commit to master?

### CODE REVIEW

**Comment by GeertJohan** [comment]
Thanks for noticing this!
Apparently I made a mistake when testing the change on compilation errors, I think I failed to pull the latest code from that branch...

I think a build check is very welcome. Wercker does about the same as Travic-CI? Should I register at wercker?

**Comment by GeertJohan** [comment]
I would like it if PR's also get built+tested...

**Comment by nwolff** [comment]
Hi, I created a second PR with the wercker config and the answer to your questions: https://github.com/GeertJohan/go.rice/pull/41

**Comment by abourget** [comment]
yeah, sorry folks.. I had applied this patch to github.com/daaku/go.zipexe without noticing, thinking it was inside `go.rice`. Maybe we can vendor in zipexe .. it's a single 135 lines file.

**Comment by GeertJohan** [comment]
Maybe first ask if @daaku is interested in adding a new constructor, e.g. `OpenCloser(..)..`?

If not, we might add just this constructor to go.rice, it uses the method NewReader which is exported.

**Comment by daaku** [comment]
Sure that seems reasonable.

**Comment by abourget** [comment]
whoops, I created a PR vendoring in `zipexe` here https://github.com/GeertJohan/go.rice/pull/42 ... it changes a bit of the semantics, but seems slightly cleaner.

What do you think ?

**Comment by daaku** [comment]
That makes `Open` unrelated to `zipexe`. Your suggested change above is what I was expecting so it's possible to close the underlying file once we're done with it and the associated `*zip.Reader`.

**Comment by GeertJohan** [comment]
Yeah, I prefer adding a new constructor in daaku/zipexe instead of vendoring zipexe to this repo.
Ofcourse combining the reader with the closer is cleaner, but that would break the existing API.

**Comment by daaku** [comment]
+1 @GeertJohan - add `zipexe.OpenCloser` and make it like https://github.com/GeertJohan/go.rice/pull/40#issuecomment-72476849

**Comment by abourget** [comment]
Fine, but `Open()` is still in a broken state.. since leaking open files is obviously a bug.

So I'll write `OpenCloser()` to fix my immediate needs, and I closed that other PR.

**Comment by daaku** [comment]
Yeah `Open` is broken, though it wasn't terrible since usually it was used to open the running binary itself and needed to survive until the binary exited anyways.
